/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class emulatorinterface_communication_shm_SharedMem */

#ifndef _Included_emulatorinterface_communication_shm_SharedMem
#define _Included_emulatorinterface_communication_shm_SharedMem
#ifdef __cplusplus
extern "C" {
#endif
#undef emulatorinterface_communication_shm_SharedMem_COUNT
#define emulatorinterface_communication_shm_SharedMem_COUNT 1000L
/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    shmget
 * Signature: (IIIJI)I
 */
JNIEXPORT jint JNICALL Java_emulatorinterface_communication_shm_SharedMem_shmget
  (JNIEnv *, jobject, jint, jint, jint, jlong, jint);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    shmat
 * Signature: (IIIIJI)J
 */
JNIEXPORT jlong JNICALL Java_emulatorinterface_communication_shm_SharedMem_shmat
  (JNIEnv *, jobject, jint, jint, jint, jint, jlong, jint);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    shmread
 * Signature: (IJI)Lemulatorinterface/communication/Packet;
 */
JNIEXPORT jobject JNICALL Java_emulatorinterface_communication_shm_SharedMem_shmread
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    shmreadMult
 * Signature: (IJII[J)V
 */
JNIEXPORT void JNICALL Java_emulatorinterface_communication_shm_SharedMem_shmreadMult
  (JNIEnv *, jclass, jint, jlong, jint, jint, jlongArray);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    tejasUpdateQueueSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_emulatorinterface_communication_shm_SharedMem_tejasUpdateQueueSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    tejasTotalProduced
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_emulatorinterface_communication_shm_SharedMem_tejasTotalProduced
  (JNIEnv *, jclass, jint);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    shmd
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_emulatorinterface_communication_shm_SharedMem_shmd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    shmdel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_emulatorinterface_communication_shm_SharedMem_shmdel
  (JNIEnv *, jclass, jint);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    asmmfence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_emulatorinterface_communication_shm_SharedMem_asmmfence
  (JNIEnv *, jclass);

/*
 * Class:     emulatorinterface_communication_shm_SharedMem
 * Method:    numPacketsAlternate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_emulatorinterface_communication_shm_SharedMem_numPacketsAlternate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
